plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  
title: Digital Technology Innovation Lab
description: "Contact: lars.ailo.bongo@uit.no"
logo: UiT_Logo_Eng_2l_Bla_RGB.png

theme: jekyll-theme-minimal
